//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetClar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeId
    {
        public int CollegeId_AutoId { get; set; }
        public string CollegeId_Id { get; set; }
        public string CollegeId_FirstName { get; set; }
        public string CollegeId_LastName { get; set; }
        public string CollegeId_DOB { get; set; }
        public string CollegeId_Gender { get; set; }
        public string CollegeId_Email { get; set; }
        public string CollegeId_Phone { get; set; }
        public string CollegeId_Type { get; set; }
        public Nullable<bool> CollegeId_IsActive { get; set; }
        public Nullable<System.DateTime> CollegeId_CreatedOn { get; set; }
        public Nullable<int> CollegeId_CreatedBy { get; set; }
        public Nullable<System.DateTime> CollegeId_ModifiedOn { get; set; }
        public Nullable<int> CollegeId_ModifiedBy { get; set; }
    }
}
