//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetClar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(MemberLoginMetaData))]
    public partial class MemberLogin
    {
        public int MemberLogin_AutoId { get; set; }
        public int MemberLogin_MemberId { get; set; }
        public string MemberLogin_Username { get; set; }
        public string MemberLogin_Password { get; set; }
        public Nullable<bool> MemberLogin_IsActive { get; set; }
        public Nullable<System.DateTime> MemberLogin_CreatedOn { get; set; }
        public Nullable<int> MemberLogin_CreatedBy { get; set; }
        public Nullable<System.DateTime> MemberLogin_ModifiedOn { get; set; }
        public Nullable<int> MemberLogin_ModifiedBy { get; set; }

        public virtual Member Member { get; set; }
    }

    public class MemberLoginMetaData
    {
        [Display(Name = "Username")]
        public string MemberLogin_Username { get; set; }
        [Display(Name = "Password")]
        public string MemberLogin_Password { get; set; }
    }
}
