//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetClar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [MetadataType(typeof(MemberMetaData))]
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberLogins = new HashSet<MemberLogin>();
            this.StaffSpecializations = new HashSet<StaffSpecialization>();
        }

        public int Member_AutoId { get; set; }
        public string Member_Firstname { get; set; }
        public string Member_Lastname { get; set; }
        public Nullable<System.DateTime> Member_DOB { get; set; }
        public string Member_Gender { get; set; }
        public string Member_CollegeId { get; set; }
        public string Member_Email { get; set; }
        public string Member_Phone { get; set; }
        public string Member_Type { get; set; }
        public string Member_StaffCategory { get; set; }
        public Nullable<int> Member_Specialization { get; set; }
        public Nullable<System.DateTime> Member_CreatedOn { get; set; }
        public Nullable<int> Member_CreatedBy { get; set; }
        public Nullable<System.DateTime> Member_ModifiedOn { get; set; }
        public Nullable<int> Member_ModifiedBy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberLogin> MemberLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffSpecialization> StaffSpecializations { get; set; }
    }

    public class MemberMetaData
    {
        [Display(Name = "First Name")]
        public string Member_Firstname { get; set; }
        [Display(Name = "Last Name")]
        public string Member_Lastname { get; set; }
        [Display(Name = "DOB")]
        public Nullable<System.DateTime> Member_DOB { get; set; }
        [Display(Name = "Gender")]
        public string Member_Gender { get; set; }
        [Display(Name = "College Id")]
        public string Member_CollegeId { get; set; }
        [Display(Name = "Email")]
        public string Member_Email { get; set; }
        [Display(Name = "Phone")]
        public string Member_Phone { get; set; }
        [Display(Name = "Member Type")]
        public string Member_Type { get; set; }
        [Display(Name = "Category")]
        public string Member_StaffCategory { get; set; }
        [Display(Name = "Specialization")]
        public Nullable<int> Member_Specialization { get; set; }
    }
}
