//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetClar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSpecialization
    {
        public int StaffSpecialization_AutoId { get; set; }
        public int StaffSpecialization_StaffId { get; set; }
        public int StaffSpecialization_SpecializationId { get; set; }
        public Nullable<System.DateTime> StaffSpecialization_CreatedOn { get; set; }
        public Nullable<int> StaffSpecialization_CreatedBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
